<a href="https://colab.research.google.com/github/oussama-marhaoui/Machine-Learning/blob/main/%20Naive%20Bayes%20Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
patient = pd.read_csv('patients.txt')
patient.head()

Douleurs Fatigue Mal de tete  Fievre Grippe ?
0      Oui     Non        Doux     Oui      Non
1      Oui     Oui       Neant     Non      Oui
2      Oui     Non        Fort     Oui      Oui
3      Non     Oui        Doux     Oui      Oui
4      Non     Non       Neant     Non      Non

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
transformer = LabelEncoder()

In [36]:
d = patient.loc[:,'Douleurs']

In [37]:
patient['Douleurs'] = transformer.fit_transform(d)

In [38]:
patient.columns[4]

'Grippe ?'

In [39]:
len(patient)

8

In [40]:
patient

Douleurs Fatigue Mal de tete  Fievre Grippe ?
0         1     Non        Doux     Oui      Non
1         1     Oui       Neant     Non      Oui
2         1     Non        Fort     Oui      Oui
3         0     Oui        Doux     Oui      Oui
4         0     Non       Neant     Non      Non
5         0     Oui        Fort     Oui      Oui
6         0     Oui        Fort     Non      Non
7         1     Oui        Doux     Oui      Oui

In [41]:
def transformer(df):
  transformer = LabelEncoder()
  for i in range(0,5):
    df[df.columns[i]] = transformer.fit_transform(df.loc[:,df.columns[i]])
  return df.head()

In [42]:
transformer(patient)

Douleurs  Fatigue  Mal de tete   Fievre  Grippe ?
0         1        0            0        1         0
1         1        1            2        0         1
2         1        0            1        1         1
3         0        1            0        1         1
4         0        0            2        0         0

In [43]:
patient.count()

Douleurs       8
Fatigue        8
Mal de tete    8
 Fievre        8
Grippe ?       8
dtype: int64

In [44]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Douleurs     8 non-null      int64
 1   Fatigue      8 non-null      int64
 2   Mal de tete  8 non-null      int64
 3    Fievre      8 non-null      int64
 4   Grippe ?     8 non-null      int64
dtypes: int64(5)
memory usage: 448.0 bytes


In [45]:
patient.columns

Index(['Douleurs', 'Fatigue', 'Mal de tete', ' Fievre', 'Grippe ?'], dtype='object')

In [46]:
patient.iloc[:,:4].describe()

Douleurs   Fatigue  Mal de tete    Fievre
count  8.000000  8.000000     8.000000  8.000000
mean   0.500000  0.625000     0.875000  0.625000
std    0.534522  0.517549     0.834523  0.517549
min    0.000000  0.000000     0.000000  0.000000
25%    0.000000  0.000000     0.000000  0.000000
50%    0.500000  1.000000     1.000000  1.000000
75%    1.000000  1.000000     1.250000  1.000000
max    1.000000  1.000000     2.000000  1.000000

In [47]:
X = patient.drop('Grippe ?', axis = 1)
y = patient['Grippe ?']

In [48]:
X.describe()

Douleurs   Fatigue  Mal de tete    Fievre
count  8.000000  8.000000     8.000000  8.000000
mean   0.500000  0.625000     0.875000  0.625000
std    0.534522  0.517549     0.834523  0.517549
min    0.000000  0.000000     0.000000  0.000000
25%    0.000000  0.000000     0.000000  0.000000
50%    0.500000  1.000000     1.000000  1.000000
75%    1.000000  1.000000     1.250000  1.000000
max    1.000000  1.000000     2.000000  1.000000

In [49]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2)

In [67]:
from sklearn.naive_bayes import GaussianNB

In [68]:
model = GaussianNB()

In [69]:
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [70]:
model.predict([(0,0,0,1)])

array([0])

In [71]:
y_pred = model.predict(X_test)
mislabel = np.sum((y_test!=y_pred))
print("Total number of mislabelled data points from {} test samples is {}".format(len(y_test),mislabel))

Total number of mislabelled data points from 2 test samples is 1


In [72]:
y_pred

array([1, 1])

In [73]:
mislabel

1

In [58]:
model.class_count_

array([5.])

In [59]:
model.class_prior_

array([1.])

In [ ]:
model.classes_

array([0, 1])

In [ ]:
model.epsilon_

3.333333333333333e-10

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print("The classification report is as follows...\n")
print(classification_report(y_test, y_pred))

The classification report is as follows...

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.17      0.50      0.25         3
weighted avg       0.11      0.33      0.17         3



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
cm = confusion_matrix(y_test, y_pred)
df = pd.DataFrame(cm, index = ['Classe 1', 'Classe 2'], columns=['Classe 1', 'Classe 2'])
print('The confusion Matrix looks like following ...')
df

The confusion Matrix looks like following ...


Classe 1  Classe 2
Classe 1         0         2
Classe 2         0         1